version: "3.0"
services:
  fastapi:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
     - "8000:8000"
    depends_on:
      - db
  rabbit:
    image: rabbitmq:latest
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=async_python
      - RABBITMQ_DEFAULT_USER=12345
    ports:
      - "5672:5672"
  db:
    container_name: "db"
    image: postgres:16.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - custom
  db_test:
    container_name: "db_test"
    image: postgres:16.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=postgres_test
    ports:
      - "5433:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge